=== fzappa/calc_mec/c++/CalcMec/dados.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="projeto" type="projetoType"/>
  <xs:complexType name="gfeixeType">
    <xs:sequence>
      <xs:element type="xs:float" name="e"/>
      <xs:element type="xs:float" name="c"/>
      <xs:element type="xs:float" name="d"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="vaoType">
    <xs:sequence>
      <xs:element type="xs:byte" name="ncfeixe"/>
      <xs:element type="xs:float" name="dfeixe"/>
      <xs:element type="gfeixeType" name="gfeixe"/>
      <xs:element type="xs:float" name="comprimento"/>
      <xs:element type="xs:float" name="h0"/>
      <xs:element type="xs:float" name="eds"/>
      <xs:element type="xs:byte" name="nl"/>
      <xs:element type="xs:float" name="tensao"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="caboType">
    <xs:sequence>
      <xs:element type="xs:string" name="modelo"/>
      <xs:element type="xs:float" name="secao"/>
      <xs:element type="xs:float" name="phi"/>
      <xs:element type="xs:float" name="massa"/>
      <xs:element type="xs:float" name="trup"/>
      <xs:element type="xs:float" name="alphafinal"/>
      <xs:element type="xs:float" name="elastfinal"/>
      <xs:element type="xs:byte" name="pminimo"/>
      <xs:element type="xs:byte" name="pmaximo"/>
      <xs:element type="xs:byte" name="tcop"/>
      <xs:element type="xs:byte" name="tamb"/>
      <xs:element type="xs:float" name="tmax"/>
      <xs:element type="xs:float" name="tmin"/>
      <xs:element type="xs:float" name="ventomed"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="projetoType">
    <xs:sequence>
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:byte" name="grafico">
        <xs:annotation>
          <xs:documentation>
      1 - PS
      2 - SVG
      3 - JPG
      4 - PNG
      5 - PDF
      6 - EPSLaTex
    </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="vaoType" name="vao"/>
      <xs:element type="caboType" name="cabo"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== fzappa/calc_mec/c++/CalcMec/Release/dados.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="dados.xsl"?>
<projeto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="dados.xsd">
    <nome>LT 765kV</nome>
    <!--
      1 - PS
      2 - SVG
      3 - JPG
      4 - PNG
      5 - PDF
      6 - EPSLaTex
    -->
    <grafico>4</grafico>
      <vao>
        <ncfeixe>4</ncfeixe>
        <dfeixe>0.457</dfeixe>
        <gfeixe>
            <e>-14.34</e>
            <c>0.0</c>
            <d>14.34</d>
        </gfeixe>
        <comprimento>300.0</comprimento>
        <h0>25.0</h0>
        <eds>20.0</eds>
        <nl>30</nl>
        <tensao>765e3</tensao>
      </vao>
      <cabo>
        <modelo>BLUEJAY</modelo>
        <secao>603.09e-6</secao>
        <phi>31.96e-3</phi>
        <massa>1867.6e-3</massa>
        <trup>13526.0</trup>
        <alphafinal>20.9e-6</alphafinal>
        <elastfinal>6628.0e6</elastfinal>
        <pminimo>76</pminimo>
        <pmaximo>108</pmaximo>
        <tcop>75</tcop>
        <tamb>25</tamb>
        <tmax>39.2</tmax>
        <tmin>-0.3</tmin>
        <ventomed>20.0</ventomed>
      </cabo>
</projeto>
